# Unit 2
date = input('Введите дату: ')
task = input('Введите задачу: ')
date1 = input('Введите дату: ')
task1 = input('Введите задачу: ')
date2 = input('Введите дату: ')
task2 = input('Введите задачу: ')
print(date+' '+task)
print(date1+' '+task1)
print(date2+' '+task2)